use_frameworks!

target 'ResizingTokenField_Example' do
  pod 'ResizingTokenField', :git => 'https://github.com/cointowitcher/ResizingTokenField'

  target 'ResizingTokenField_Tests' do
    inherit! :search_paths

    
  end
end
